perfil-leonardo-gusso
programadoreszica/meu-perfil pull request #3
Opened 2022-08-03 23:33 UTC by leonardo-gusso

2022-08-03 23:49 UTC, techadelle requested changes

2022-08-03 23:49 UTC, techadelle commented on Leonardo/Index.html
> +
leo gentileza excluir linha 15

2022-08-03 23:49 UTC, techadelle commented on Leonardo/Index.html
> +            <a href="https://www.linkedin.com/in/leonardo-gusso-de-souza-56b6b1237/">
Corrigir espaço inicio e fim linha 21

2022-08-04 00:08 UTC, leonardo-gusso commented on Leonardo/Index.html
> +            <a href="https://www.linkedin.com/in/leonardo-gusso-de-souza-56b6b1237/">
Feito.

2022-08-04 00:12 UTC, techadelle approved these changes
Lgtm

2022-08-04 00:12 UTC, merged